"""
Document exporters — slide deck, PDF report and templated manuscript.

All generated locally from content the pipeline already produced (sections,
papers, synthesis). No LLM calls here, so exporting costs nothing.

Formats:
  build_pptx()  -> slide deck (.pptx)
  build_pdf()   -> formatted report (.pdf)
  build_docx()  -> manuscript in an IEEE / arXiv style template (.docx)
"""
import io
import re
from datetime import date

SECTION_ORDER = [
    ("abstract", "Abstract"),
    ("intro", "Introduction"),
    ("synthesis", "Literature Review"),
    ("gaps", "Gaps and Limitations"),
    ("future", "Future Directions and Conclusion"),
]

ACCENT = (0x5B, 0x4F, 0xF0)


# ── helpers ────────────────────────────────────────────────────────────────

def _paras(text: str) -> list[str]:
    return [p.strip() for p in re.split(r"\n\s*\n", text or "") if p.strip()]


def review_title(sections: dict, topic: str) -> str:
    return (sections or {}).get("title") or (topic or "Literature Review")


def reference_list(papers: list[dict]) -> list[str]:
    """IEEE-style numbered references in citation order."""
    out = []
    for i, p in enumerate(papers or [], 1):
        authors = p.get("authors") or "—"
        title = p.get("title") or ""
        venue = p.get("venue") or "preprint"
        year = p.get("year") or "n.d."
        out.append(f'[{i}] {authors}, "{title}," {venue}, {year}.')
    return out


# ── PPTX ───────────────────────────────────────────────────────────────────

def build_pptx(topic: str, sections: dict, papers: list[dict], synthesis: dict) -> bytes:
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor

    prs = Presentation()
    prs.slide_width, prs.slide_height = Inches(13.333), Inches(7.5)   # 16:9
    accent = RGBColor(*ACCENT)
    title = review_title(sections, topic)

    def bullets_slide(heading, bullets, note=None):
        s = prs.slides.add_slide(prs.slide_layouts[1])
        s.shapes.title.text = heading
        s.shapes.title.text_frame.paragraphs[0].runs[0].font.size = Pt(30)
        s.shapes.title.text_frame.paragraphs[0].runs[0].font.color.rgb = accent
        body = s.placeholders[1].text_frame
        body.word_wrap = True
        first = True
        for b in bullets:
            p = body.paragraphs[0] if first else body.add_paragraph()
            p.text = b
            p.font.size = Pt(16)
            first = False
        if note:
            s.notes_slide.notes_text_frame.text = note
        return s

    # Title slide
    s0 = prs.slides.add_slide(prs.slide_layouts[0])
    s0.shapes.title.text = title
    s0.shapes.title.text_frame.paragraphs[0].runs[0].font.size = Pt(38)
    s0.shapes.title.text_frame.paragraphs[0].runs[0].font.color.rgb = accent
    s0.placeholders[1].text = (
        f"A literature review of {len(papers)} sources\n"
        f"Generated by Saṃhitā · {date.today().isoformat()}"
    )

    # Content slides from each written section
    for key, label in SECTION_ORDER:
        text = (sections or {}).get(key)
        if not text:
            continue
        chunks = _paras(text)
        # split long sections across slides (max ~5 bullets each)
        bullets = []
        for c in chunks:
            for sent in re.split(r"(?<=[.!?])\s+", c):
                sent = sent.strip()
                if len(sent) > 12:
                    bullets.append(sent if len(sent) <= 220 else sent[:217] + "…")
        for n in range(0, len(bullets), 5):
            part = bullets[n:n + 5]
            head = label if n == 0 else f"{label} (cont.)"
            bullets_slide(head, part)

    # Themes & gaps from the synthesis
    themes = (synthesis or {}).get("themes") or []
    gaps = (synthesis or {}).get("gaps") or []
    if themes:
        bullets_slide("Key Themes", [str(t) for t in themes[:6]])
    if gaps:
        bullets_slide("Research Gaps", [str(g) for g in gaps[:6]])

    # References (chunked)
    refs = reference_list(papers)
    for n in range(0, len(refs), 8):
        bullets_slide("References" if n == 0 else "References (cont.)", refs[n:n + 8])

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()


# ── PDF ────────────────────────────────────────────────────────────────────

def build_pdf(topic: str, sections: dict, papers: list[dict], synthesis: dict) -> bytes:
    from reportlab.lib.pagesizes import LETTER
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, HRFlowable)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=LETTER, title=review_title(sections, topic),
        leftMargin=0.9 * inch, rightMargin=0.9 * inch,
        topMargin=0.85 * inch, bottomMargin=0.85 * inch,
    )
    ss = getSampleStyleSheet()
    accent = colors.Color(ACCENT[0] / 255, ACCENT[1] / 255, ACCENT[2] / 255)
    h_title = ParagraphStyle("t", parent=ss["Title"], fontSize=19, leading=24, textColor=accent)
    h_sec = ParagraphStyle("s", parent=ss["Heading2"], fontSize=13, leading=17,
                           spaceBefore=14, spaceAfter=6, textColor=accent)
    body = ParagraphStyle("b", parent=ss["BodyText"], fontSize=10.5, leading=15.5,
                          alignment=4, spaceAfter=8)        # justified
    small = ParagraphStyle("m", parent=ss["BodyText"], fontSize=9, textColor=colors.grey)
    ref = ParagraphStyle("r", parent=body, leftIndent=18, firstLineIndent=-18, spaceAfter=4)

    def esc(t):
        return (t or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    story = [Paragraph(esc(review_title(sections, topic)), h_title)]
    story.append(Paragraph(
        f"A literature review of {len(papers)} sources · generated by Saṃhitā · {date.today().isoformat()}",
        small))
    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", color=accent, thickness=1))

    for key, label in SECTION_ORDER:
        text = (sections or {}).get(key)
        if not text:
            continue
        story.append(Paragraph(label, h_sec))
        for p in _paras(text):
            story.append(Paragraph(esc(p), body))

    if papers:
        story.append(Paragraph("References", h_sec))
        for r in reference_list(papers):
            story.append(Paragraph(esc(r), ref))

    doc.build(story)
    return buf.getvalue()


# ── DOCX (IEEE / arXiv templates) ──────────────────────────────────────────

def build_docx(topic: str, sections: dict, papers: list[dict], synthesis: dict,
               template: str = "ieee") -> bytes:
    from docx import Document
    from docx.enum.section import WD_SECTION
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.shared import Pt, Inches, RGBColor

    tpl = (template or "ieee").lower()
    doc = Document()
    title = review_title(sections, topic)

    # Page + base font per template
    sec = doc.sections[0]
    for m in ("top_margin", "bottom_margin", "left_margin", "right_margin"):
        setattr(sec, m, Inches(0.75 if tpl == "ieee" else 1.0))
    normal = doc.styles["Normal"]
    normal.font.name = "Times New Roman"
    normal.font.size = Pt(10 if tpl == "ieee" else 11)

    # ── Title block (single column, even in IEEE) ──
    t = doc.add_paragraph()
    t.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = t.add_run(title)
    run.font.size = Pt(20 if tpl == "ieee" else 17)
    run.font.bold = True

    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    mrun = meta.add_run(f"Generated by Saṃhitā · {len(papers)} sources · {date.today().isoformat()}")
    mrun.font.size = Pt(9)
    mrun.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    # IEEE is two-column from the abstract onward
    if tpl == "ieee":
        new = doc.add_section(WD_SECTION.CONTINUOUS)
        cols = new._sectPr.xpath("./w:cols")[0]
        cols.set(_qn("w:num"), "2")
        cols.set(_qn("w:space"), "360")          # ~0.25"
        for m in ("top_margin", "bottom_margin", "left_margin", "right_margin"):
            setattr(new, m, Inches(0.75))

    def heading(text, n=1):
        h = doc.add_paragraph()
        r = h.add_run(text.upper() if tpl == "ieee" else text)
        r.font.bold = True
        r.font.size = Pt(10 if tpl == "ieee" else 13)
        if tpl == "ieee":
            h.alignment = WD_ALIGN_PARAGRAPH.CENTER
        h.paragraph_format.space_before = Pt(10)
        h.paragraph_format.space_after = Pt(4)

    def para(text, italic=False, bold_lead=None):
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
        p.paragraph_format.first_line_indent = Inches(0.2 if tpl == "ieee" else 0)
        p.paragraph_format.space_after = Pt(6)
        if bold_lead:
            b = p.add_run(bold_lead)
            b.font.bold = True
            b.font.italic = True
        r = p.add_run(text)
        r.font.italic = italic
        return p

    # ── Abstract ──
    if sections.get("abstract"):
        for i, blk in enumerate(_paras(sections["abstract"])):
            para(blk, italic=(tpl == "ieee"), bold_lead="Abstract— " if (tpl == "ieee" and i == 0) else None)

    # Index terms (IEEE convention) from synthesis themes
    themes = [str(t) for t in ((synthesis or {}).get("themes") or [])][:5]
    if themes and tpl == "ieee":
        para(", ".join(themes) + ".", italic=True, bold_lead="Index Terms— ")

    # ── Body sections ──
    numbered = ["I.", "II.", "III.", "IV.", "V.", "VI."]
    n = 0
    for key, label in SECTION_ORDER:
        if key == "abstract" or not sections.get(key):
            continue
        prefix = f"{numbered[n]} " if (tpl == "ieee" and n < len(numbered)) else ""
        heading(prefix + label)
        n += 1
        for blk in _paras(sections[key]):
            para(blk)

    # ── References ──
    if papers:
        heading(f"{numbered[n]} References" if (tpl == "ieee" and n < len(numbered)) else "References")
        for r in reference_list(papers):
            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
            p.paragraph_format.left_indent = Inches(0.25)
            p.paragraph_format.first_line_indent = Inches(-0.25)
            p.paragraph_format.space_after = Pt(3)
            run = p.add_run(r)
            run.font.size = Pt(8.5 if tpl == "ieee" else 10)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def _qn(tag: str):
    from docx.oxml.ns import qn
    return qn(tag)
