import React from "react";

const ORDER = [
  ["abstract", "Abstract"],
  ["intro", "Introduction"],
  ["synthesis", "Thematic synthesis"],
  ["gaps", "Gaps & limitations"],
  ["future", "Future directions & conclusion"],
];

function linkCites(text) {
  const parts = text.split(/(\[\d+(?:,\s*\d+)*\])/g);
  return parts.map((part, i) =>
    /^\[\d/.test(part) ? <span key={i} className="ref">{part}</span> : <React.Fragment key={i}>{part}</React.Fragment>
  );
}

function renderParagraphs(text) {
  return (text || "").split(/\n\s*\n/).filter(Boolean).map((para, i) => <p key={i}>{linkCites(para)}</p>);
}

export default function ReviewView({ topic, sections, citeOrder }) {
  return (
    <div className="review">
      {/* Prefer the writer's generated academic title; fall back to the topic. */}
      <h4 className="serif" style={sections?.title ? null : { textTransform: "capitalize" }}>
        {sections?.title || topic}
      </h4>
      <div className="sub">A literature review · {citeOrder.length} sources · generated by Sift</div>

      {ORDER.map(([key, label]) =>
        sections[key] ? (
          <section key={key}>
            <div className="sec-h">{label}</div>
            {renderParagraphs(sections[key])}
          </section>
        ) : null
      )}

      <section>
        <div className="sec-h">References</div>
        <div className="refs">
          {citeOrder.map((p, i) => (
            <div key={p.idx} className="r">
              <b>[{i + 1}]</b>
              <span>{p.authors || "—"}, “{p.title},” {p.venue || "preprint"}, {p.year || "n.d."}.</span>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
